### PR TITLE
[v1] Release

### PR DESCRIPTION
**Pull request by rafaelsideguide**

### CODE REVIEW

**Comment by KentHsu** [comment]
Hi @rafaelsideguide, glad you reached out! I have some suggestions for the changes.
Since Go follows the [convention](https://go.dev/blog/publishing-go-modules) of Semantic Versioning, v0 is considered an unstable version, while v1 represents a commitment to future compatibility. I suggest we tag a release for v0 and then move on to v1, so the code for the two versions doesn’t mix together.
If we really need to maintain v0 for some reason, Go has another [convention](https://go.dev/blog/v2-go-modules) for creating subfolders for v2+ releases. Following this concept, we could create a v0 subfolder, allowing the code to coexist in the same project, and users can import the v0 code from different paths. However, I don't see this approach used very often because v0 is considered an unstable version.

**Comment by rafaelsideguide** [comment]
@KentHsu that makes a lot of sense. First, I'm going to release v0. After that, I'll remove the v0-specific code from the new version. I'll also apply this approach to the other SDKs. Thanks a lot for your input!

**Comment by KentHsu** [comment]
Absolutely! Looking forward to contributing to Firecrawl too. Please don't hesitate to reach out if you need a hand on the development.

**Comment by rafaelsideguide** [comment]
@KentHsu hey, could you take a look at this PR?  I'm about to merge it, but I would appreciate your review.

**Pull request merged**
